### ISSUE TITLE
Where to add openrouteservice itself?

### ISSUE THREAD

**Issue by cemrehancavdar** [sacridini/Awesome-Geospatial#109]
I've added openrouteservice's development side within #108. but couldn't be sure where should i added itself.

And as a second question it has QGIS Plugin. We've some QGIS plugins on list. What is our stance on this matter, choosing a QGIS plugin to included? @sacridini 

Wish all you all a great week! 🥳

**Comment by sacridini** [comment]
Hey @cemrehancavdar! How are you? :) 
Sorry for the delayed response.

So I usually add these more "generic" tools that are not a library associated with a specific language in the "tools" category

I think it's possible to add QGIS plugins too, not sure about an entire section for this, but I think it can be added within the "tools" sections too.

Have a great weekend! 👍🏼

**Comment by cemrehancavdar** [comment]
Hey, @sacridini
Feeling great, Thanks for answer! wbu?
It's quite nice approach to add more generic tools. I'll try to look by that way.
Have a good week ✌️
