### ISSUE TITLE
Add geoapify

### ISSUE THREAD

**Issue by kinsvater** [sacridini/Awesome-Geospatial#113]
Hi Eduardo,

I have created a CLI and Python client for the Geoapify web services: https://github.com/huels-originals/geoapify.

See the tutorials in the docs to get an idea: https://geoapify.readthedocs.io/en/latest/example-toy/

If you have not heard about Geoapify yet: it offers for batch geocoding and more, integrates well with GeoJSON, is powered by the OpenStreetMap ecosystem, and has a very generous free tier plus a super-friendly license.

I would appreciate it if you add this package to your Python list. Many thanks!

**Comment by sacridini** [comment]
I saw that you already added the library to the list. Thanks for the contribution! :)
