### ISSUE TITLE
Open Datasets for Autonomous Driving

### ISSUE THREAD

**Issue by chrieke** [sacridini/Awesome-Geospatial#26]
Not entirely sure if this should be on the list. Definitely an amazing ressource and a lot of stuff that can be labeled geospatial.

https://scale.com/open-datasets?utm_campaign=Spatial%20Awareness&utm_medium=email&utm_source=Revue%20newsletter

**Comment by sacridini** [comment]
Fantastic datasets resource. I will definitely add this to the data source section. :)
