### ISSUE TITLE
Add tmap to R section

### ISSUE THREAD

**Issue by RPanczak** [sacridini/Awesome-Geospatial#49]
Might be worth adding mighty `tmap` package into R section? 
CRAN: https://cran.r-project.org/web/packages/tmap/index.html
GH: https://github.com/mtennekes/tmap

Also connected to it is `tmaptools`
https://cran.r-project.org/web/packages/tmaptools/index.html
https://github.com/mtennekes/tmaptools

**Comment by sacridini** [comment]
Just added the two packages. Thanks for the tip. 👍

**Comment by RPanczak** [comment]
👍

**Comment by RPanczak** [comment]
Since we are on the topic I's also suggest `mapview` https://r-spatial.github.io/mapview/index.html
