### ISSUE TITLE
Some additional Microsoft resources

### ISSUE THREAD

**Issue by rbrundritt** [sacridini/Awesome-Geospatial#6]
Noticed your list on the weekend. You mention Bing Maps a couple of times, but here are a few other Bing Maps and Microsoft mapping resources that might be useful:

Under Database

- May be good to mention Microsoft SQL Server or SQL Azure, these both have a  bunch of powerful spatial features built-in. 
   - https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-data-sql-server
   - All the spatial functionality is also available as a .NET library here: https://www.nuget.org/packages/Microsoft.SqlServer.Types

Under Paas

- You have Microsoft Bing API listed, but it points to the Bing Maps portal where you would sign up for an account. A higherlevel website with more details on Bing Maps can befound here: https://www.microsoft.com/en-us/maps This may be a better link to point users to initially.

Under C Sharp these may be useful:

- [Windows UWP map control](https://msdn.microsoft.com/en-us/library/windows/apps/xaml/dn642089.aspx) - The Bing Maps control built into the Windows UWP platform.
- [Bing Maps WPF SDK](https://msdn.microsoft.com/en-us/library/hh750210.aspx) - The Bing Maps WPF API
- [Bing Maps REST Toolkit](https://github.com/Microsoft/BingMapsRESTToolkit) - This is a portable class library which makes it easy to access the Bing Maps REST services from .NET. 
- [Bing Maps Spatial Data Services Toolkit](https://github.com/Microsoft/BingMapsSDSToolkit) - This toolkit makes it easy to use the Bing Maps Spatial Data Services (SDS) in .NET
- [BotBuild-Location](https://github.com/Microsoft/BotBuilder-Location) - An open-source location picker control for Microsoft Bot Framework powered by Bing Maps REST services. 

Under JavaScript

- [Bing Maps V8 Web Control](https://msdn.microsoft.com/en-us/library/mt712542.aspx) - Bing Maps API for JavaScript
- [Bing Maps V8 Interactive SDK](https://www.bing.com/api/maps/sdkrelease/mapcontrol/isdk#overview) - An interactive code sample gallery for Bing Maps V8.
- [Bing Maps V8 Code Samples](https://github.com/Microsoft/BingMapsV8CodeSamples) - A large collection of open source code samples for Bing Maps V8.
- [Bing Maps V8 TypeScript Definitions](https://github.com/Microsoft/Bing-Maps-V8-TypeScript-Definitions) - TypeScript Definitions for the Bing Maps V8 web control. 

Hope you find these useful. 

Cheers,
Ricky

**Comment by sacridini** [comment]
Thanks for the contribution Ricky! A lot of good stuff :) 
I'll update the list
Cheers,
Eduardo
