### ISSUE TITLE
Should include ESA SNAP for image analysis

### ISSUE THREAD

**Issue by M2FXKY** [sacridini/Awesome-Geospatial#70]
Hi, Sentinel toolboxes are included, but I would also include/replace them with SNAP, which basically regroups all SxTBXs and other tools under a unique package. > https://step.esa.int/main/download/snap-download/

Thanks by the way for the handy list.

**Comment by sacridini** [comment]
Added SNAP to the list. Thanks for the contribution! :)

Best,
Edu
