### ISSUE TITLE
Orfeo Toolbox (OTB) is released under Apache v2.0 license

### ISSUE THREAD

**Issue by sdinot** [sacridini/Awesome-Geospatial#71]
Thank you very much for this very rich collection of links.

The Orfeo Toolbox (OTB) project is referenced in the C++ libraries section and it is reported that this set of libraries are released under CeCILL v2.0 license. This information was once accurate, but OTB libraries are now released under the Apache v2.0 license (cf. [LICENSE file](https://gitlab.orfeo-toolbox.org/orfeotoolbox/otb/blob/develop/LICENSE) in the source code repository). [The change](https://gitlab.orfeo-toolbox.org/orfeotoolbox/otb/-/commit/2e362de9282b0b5e8851d7a311ee235832971ea2) was made more than 4 years ago now.

Could you update this information? It is important because the CeCILL license was a strong copyleft license almost unknown outside France, whereas the Apache license is a permissive license with a worldwide reputation.

Thank you in advance.

**Comment by sacridini** [comment]
Updated! Thanks for the contribution Sébastien.
