### ISSUE TITLE
add packages to R section

### ISSUE THREAD

**Issue by rafapereirabr** [sacridini/Awesome-Geospatial#84]
Hi Eduardo. Here are a few packages for spatial analysis that I thought you might wanna add to the R section.

- [r5r: Rapid realistic routing on multimodal transport networks with R5](https://github.com/ipeaGIT/r5r)
- [gtfs2gps: Converting Transport Data from GTFS Format to GPS-Like Records](https://github.com/ipeaGIT/gtfs2gps)
- [geobr: Download Official Spatial Data Sets of Brazil](https://github.com/ipeaGIT/geobr)

**Comment by sacridini** [comment]
Hi Rafael. I just added the packages to the list. Thanks a lot for your contribution! :)
